version: '3.6'
services:
  neo4j:
    container_name: neo4j
    image: "cedar-neo4j:${CEDAR_DOCKER_VERSION}"
    build:
       context: ${CEDAR_HOME}/cedar-docker-build/infrastructure/cedar-neo4j
       args:
          CEDAR_NEO4J_USER_NAME:      ${CEDAR_NEO4J_USER_NAME}
          CEDAR_NEO4J_USER_PASSWORD:  ${CEDAR_NEO4J_USER_PASSWORD}
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NEO4J_REST_PORT}:7474
      - ${CEDAR_NEO4J_BOLT_PORT}:7687



networks:
  cedarnet:
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet:  ${CEDAR_NET_SUBNET}/24
#         gateway: ${CEDAR_NET_GATEWAY}