version: '3.6'
services:


  elasticsearch:
    container_name: elasticsearch
    image: "cedar-elasticsearch:${CEDAR_DOCKER_VERSION}"
    build:
        context:  ${CEDAR_HOME}/cedar-docker-build/infrastructure/cedar-elasticsearch
    networks:
      - cedarnet
    ports:
      - ${CEDAR_ELASTICSEARCH_REST_PORT}:9200
      - ${CEDAR_ELASTICSEARCH_TRANSPORT_PORT}:9300


networks:
  cedarnet:
    name: cedarnet
    driver: bridge
    ipam:
      driver: default
      config:
         - subnet:  ${CEDAR_NET_SUBNET}/24
#         gateway: ${CEDAR_NET_GATEWAY}