version: '3.6'
services:

  mysql:
    container_name: mysql
    image: "cedar-mysql:${CEDAR_DOCKER_VERSION}"
    build:
        context: ${CEDAR_HOME}/cedar-docker-build/infrastructure/cedar-mysql
        args:
           CEDAR_MYSQL_ROOT_PASSWORD:      ${CEDAR_MYSQL_ROOT_PASSWORD}
           CEDAR_KEYCLOAK_MYSQL_USER:      ${CEDAR_KEYCLOAK_MYSQL_USER}
           CEDAR_KEYCLOAK_MYSQL_PASSWORD:  ${CEDAR_KEYCLOAK_MYSQL_PASSWORD}
           CEDAR_KEYCLOAK_MYSQL_DB:        ${CEDAR_KEYCLOAK_MYSQL_DB}
           CEDAR_MESSAGING_MYSQL_USER:     ${CEDAR_MESSAGING_MYSQL_USER}
           CEDAR_MESSAGING_MYSQL_PASSWORD: ${CEDAR_MESSAGING_MYSQL_PASSWORD}
           CEDAR_MESSAGING_MYSQL_DB:       ${CEDAR_MESSAGING_MYSQL_DB}
           CEDAR_LOG_MYSQL_USER:           ${CEDAR_LOG_MYSQL_USER}
           CEDAR_LOG_MYSQL_PASSWORD:       ${CEDAR_LOG_MYSQL_PASSWORD}
           CEDAR_LOG_MYSQL_DB:             ${CEDAR_LOG_MYSQL_DB}
    networks:
       - cedarnet
    ports:
      - "3306:3306"

networks:
  cedarnet:
    external:
      name: cedarnet
