#!/bin/bash

cmd="mysqld --user=mysql --datadir=${MYSQL_DATA_DIR}"
$cmd  &

mysqladmin --wait --user root password ${CEDAR_MYSQL_ROOT_PASSWORD}

mysql -u root --password=${CEDAR_MYSQL_ROOT_PASSWORD} <<EOF

CREATE DATABASE IF NOT EXISTS ${CEDAR_KEYCLOAK_MYSQL_DB}; 
CREATE  USER "${CEDAR_KEYCLOAK_MYSQL_USER}" IDENTIFIED BY "${CEDAR_KEYCLOAK_MYSQL_PASSWORD}";
GRANT ALL PRIVILEGES ON ${CEDAR_KEYCLOAK_MYSQL_DB}.* TO "${CEDAR_KEYCLOAK_MYSQL_USER}";

CREATE DATABASE IF NOT EXISTS ${CEDAR_LOG_MYSQL_DB};
CREATE USER "${CEDAR_LOG_MYSQL_USER}" IDENTIFIED BY "${CEDAR_LOG_MYSQL_PASSWORD}";
GRANT ALL PRIVILEGES ON ${CEDAR_LOG_MYSQL_DB}.* TO "${CEDAR_LOG_MYSQL_USER}";

CREATE DATABASE IF NOT EXISTS ${CEDAR_MESSAGING_MYSQL_DB};
CREATE USER "${CEDAR_MESSAGING_MYSQL_USER}" IDENTIFIED BY "${CEDAR_MESSAGING_MYSQL_PASSWORD}";
GRANT ALL PRIVILEGES ON ${CEDAR_MESSAGING_MYSQL_DB}.* TO "${CEDAR_MESSAGING_MYSQL_USER}";

FLUSH PRIVILEGES;
EOF

mysqladmin --user root --password=${CEDAR_MYSQL_ROOT_PASSWORD} shutdown
