version: '3.6'
services:
  redis:
    container_name: redis
    image: "redis:6"
    networks:
      - cedarnet
    ports:
      - 6379:6379

  mysql:
    container_name: mysql
    image: "cedar-mysql:${CEDAR_DOCKER_VERSION}"
    build:
        context: ${CEDAR_SOURCE}/cedar-dev-root/infrastructure/cedar-mysql
        args:
           CEDAR_MYSQL_ROOT_PASSWORD:      ${CEDAR_MYSQL_ROOT_PASSWORD}
           CEDAR_KEYCLOAK_MYSQL_USER:      ${CEDAR_KEYCLOAK_MYSQL_USER}
           CEDAR_KEYCLOAK_MYSQL_PASSWORD:  ${CEDAR_KEYCLOAK_MYSQL_PASSWORD}
           CEDAR_KEYCLOAK_MYSQL_DB:        ${CEDAR_KEYCLOAK_MYSQL_DB}
           CEDAR_MESSAGING_MYSQL_USER:     ${CEDAR_MESSAGING_MYSQL_USER}
           CEDAR_MESSAGING_MYSQL_PASSWORD: ${CEDAR_MESSAGING_MYSQL_PASSWORD}
           CEDAR_MESSAGING_MYSQL_DB:       ${CEDAR_MESSAGING_MYSQL_DB}
           CEDAR_LOG_MYSQL_USER:           ${CEDAR_LOG_MYSQL_USER}
           CEDAR_LOG_MYSQL_PASSWORD:       ${CEDAR_LOG_MYSQL_PASSWORD}
           CEDAR_LOG_MYSQL_DB:             ${CEDAR_LOG_MYSQL_DB}

           MYSQL_CERTS:                    /opt/mysql/keys
    volumes:
       - certs_and_keys_mysql:/opt/mysql/keys
    networks:
       - cedarnet
    ports:
      - "3306:3306"

  elasticsearch:
    container_name: elasticsearch
    image: "cedar-elasticsearch:${CEDAR_DOCKER_VERSION}"
    build:
        context:  ${CEDAR_SOURCE}/cedar-dev-root/infrastructure/cedar-elasticsearch
    networks:
      - cedarnet
    ports:
      - ${CEDAR_ELASTICSEARCH_REST_PORT}:9200
      - ${CEDAR_ELASTICSEARCH_TRANSPORT_PORT}:9300

  mongo:
    container_name: mongo
    image: "cedar-mongo:${CEDAR_DOCKER_VERSION}"
    build:
        context: ${CEDAR_SOURCE}/cedar-dev-root/infrastructure/cedar-mongo
        args:
           CEDAR_MONGO_ROOT_USER_NAME:      ${CEDAR_MONGO_ROOT_USER_NAME}
           CEDAR_MONGO_ROOT_USER_PASSWORD:  ${CEDAR_MONGO_ROOT_USER_PASSWORD}
           CEDAR_MONGO_APP_USER_NAME:       ${CEDAR_MONGO_APP_USER_NAME}
           CEDAR_MONGO_APP_USER_PASSWORD:   ${CEDAR_MONGO_APP_USER_PASSWORD}
    networks:
      - cedarnet
    ports:
      - "${CEDAR_MONGO_PORT}:27017"

  neo4j:
    container_name: neo4j
    image: "cedar-neo4j:${CEDAR_DOCKER_VERSION}"
    build:
       context: ${CEDAR_SOURCE}/cedar-dev-root/infrastructure/cedar-neo4j
       args:
          CEDAR_NEO4J_USER_NAME:      ${CEDAR_NEO4J_USER_NAME}
          CEDAR_NEO4J_USER_PASSWORD:  ${CEDAR_NEO4J_USER_PASSWORD}
    networks:
      - cedarnet
    ports:
      - ${CEDAR_NEO4J_REST_PORT}:7474
      - ${CEDAR_NEO4J_BOLT_PORT}:7687


  keycloak:
    container_name: keycloak
    image: "cedar-keycloak:${CEDAR_DOCKER_VERSION}"
    depends_on:
       - mysql
    build:
      context: ${CEDAR_SOURCE}/cedar-dev-root/infrastructure/cedar-keycloak
      args:
        CEDAR_KEYCLOAK_ADMIN_USER:     ${CEDAR_KEYCLOAK_ADMIN_USER}
        CEDAR_KEYCLOAK_ADMIN_PASSWORD: ${CEDAR_KEYCLOAK_ADMIN_PASSWORD}
        CEDAR_KEYCLOAK_MYSQL_USER:     ${CEDAR_KEYCLOAK_MYSQL_USER}
        CEDAR_KEYCLOAK_MYSQL_PASSWORD: ${CEDAR_KEYCLOAK_MYSQL_PASSWORD}
        CEDAR_KEYCLOAK_MYSQL_DB:       ${CEDAR_KEYCLOAK_MYSQL_DB}
        CEDAR_NET_GATEWAY:             ${CEDAR_NET_GATEWAY}
        CEDAR_NET_SUBNET:              ${CEDAR_NET_SUBNET}

        CEDAR_KEYCLOAK_MYSQL_HOST:     ${CEDAR_KEYCLOAK_MYSQL_HOST}
        CEDAR_KEYCLOAK_MYSQL_PORT:     ${CEDAR_KEYCLOAK_MYSQL_PORT}
        CEDAR_RESOURCE_ADMIN_PORT:     ${CEDAR_RESOURCE_ADMIN_PORT}
        CEDAR_RESOURCE_HTTP_PORT:      ${CEDAR_RESOURCE_HTTP_PORT}
        CEDAR_RESOURCE_STOP_PORT:      ${CEDAR_RESOURCE_STOP_PORT}
        CEDAR_ADMIN_USER_API_KEY:      ${CEDAR_ADMIN_USER_API_KEY}
    networks:
      - cedarnet
    ports:
      - "8080:8080"
      - "8443:8443"

  nginx:
    container_name: nginx
    image: "cedar-nginx:${CEDAR_DOCKER_VERSION}"
    build:
        context: ${CEDAR_SOURCE}/cedar-dev-root/infrastructure/cedar-nginx
        args:
          CEDAR_CERTS_VOL:             /opt/certs
    networks:
       - cedarnet
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs_and_keys_nginx:/opt/certs


networks:
  cedarnet:
    external: true
    name: cedarnet

volumes:
  certs_and_keys_mysql:
    external: true
  certs_and_keys_nginx:
    external: true
  certs_and_keys_keycloak:
    external: true
