version: "3.9"
services:
  ca:
    container_name: ca
    image: "cedar-ca:${CEDAR_DOCKER_VERSION}"
    build:
      context: ${CEDAR_SOURCE}/cedar-dev-root/setup/ca
      args:
        CEDAR_CA_PASSWORD:                 ${CEDAR_CA_PASSWORD}
        CEDAR_KEYCLOAK_KEYSTORE_PASSWORD:  ${CEDAR_KEYCLOAK_KEYSTORE_PASSWORD}
        CEDAR_CA:                          /var/ca
        MYSQL_CERTS:                       /var/certs/mysql
        NGINX_CERTS:                       /var/certs/nginx
        KEYCLOAK_CERTS:                    /var/certs/keycloak
    networks:
      - cedarnet
    volumes:
      - cedar_ca:/var/ca
      - certs_and_keys_mysql:/var/certs/mysql
      - certs_and_keys_nginx:/var/certs/nginx
      - certs_and_keys_keycloak:/var/certs/keycloak

networks:
  cedarnet:
    external: true
    name: cedarnet

volumes:
  cedar_ca:
    external: true
  certs_and_keys_mysql:
    external: true
  certs_and_keys_nginx:
    external: true
  certs_and_keys_keycloak:
    external: true
